language: java
jdk:
- openjdk8
install:
- "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
script:
- "./mvnw test -B"
deploy:
  provider: heroku
  api_key:
    secure: WGmwsNj+JHGvq3WfJgHzfRbZ5kgazpgoEMrAykq8AROWWhszckf56s2rcECDPbUmvLQwj5kLzB33iB7VplYMnt+HsuwfT1714E2Ehy4gBInKbdnwWvn4oLJv2y5CFESGK/tgSuFnP8G4+vT2lRKEKu6G7SExfGnQVtn3rAOqMNh1rEOBLX4GfOH6S6b4qhftEWspf2JOtpSZqhd4r6XXXgHd13cdkNaXWOdU4Aivbs93tyKLwuM+qFz8WfFCLN8bBg+NFNlnEmMjR16zyx9/gzlOW3cnQovJZOAccaXzefBQYRVTX3L1kVmrz5qNyjXxV2BGOqGRCM3W93zm9do0XFXdzE1vNkBgq4kOrP+Qh7dzbwdn0SkwyX5VoOsCGHgspCAuEAb3/NXT3lMhbomDrFx4td2sa56JUdvvQxTQY9oSrSOTKyznjw96ulyBXfkbXRfCPLKRPAF2b7JNObtKTd9YHqz+s+sELpLXidgEjSzTiZ30Yj3kHWCBJCLEQx4tfCI7MrGJWYGTmilV8aoogGWvmgXUpznCbNqTXNBlgEB2GOiUvcb+oQfv3rTsGcej2CyLLhjh72st40ieqnjs4UaLoKgn06qXwJ/oqWi5pntc8XF/5o2jPB/s5GOUL8U6A4x+j/ky4K+WPU306ByjuoxqW+gJqpAL18QRknJdMV8=
  app: mapfood
